# Generated by Django 4.1.5 on 2023-01-12 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posteos", "0009_alter_userprofile_imagen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=150, null=True)),
                ("asunto", models.CharField(blank=True, max_length=50, null=True)),
                ("cuerpo", models.TextField(blank=True, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "de",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "para",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="posteos.userprofile",
                    ),
                ),
            ],
        ),
    ]
