# Generated by Django 4.1.5 on 2023-01-09 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posteos", "0002_remove_post_autor_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="fecha",
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("fecha_nacimiento", models.DateField()),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="usuarios-imagen"
                    ),
                ),
                ("fecha_creado", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
