# Generated by Django 4.1.5 on 2023-01-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0003_alter_post_fecha_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
