# Generated by Django 4.1.5 on 2023-01-10 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0004_userprofile_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="descripcion",
        ),
    ]
