# Generated by Django 4.1.5 on 2023-01-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0005_remove_userprofile_descripcion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="nombre_usuario",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
