# Generated by Django 4.1.5 on 2023-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0006_alter_userprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nombre_usuario",
            field=models.CharField(
                blank=True, default="username", max_length=50, null=True
            ),
        ),
    ]
