# Generated by Django 4.1.5 on 2023-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0007_alter_userprofile_nombre_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="user-defoult.png",
                null=True,
                upload_to="usuarios-imagen",
            ),
        ),
    ]
