# Generated by Django 4.1.5 on 2023-01-12 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posteos", "0008_alter_userprofile_imagen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="user_defoult.png",
                null=True,
                upload_to="usuarios-imagen",
            ),
        ),
    ]
